
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-ingredient-instruction-classifier
  labels:
    app: rs-ingredient-instruction-classifier
spec:
  selector:
    matchLabels:
      app: rs-ingredient-instruction-classifier
  template:
    metadata:
      labels:
        app: rs-ingredient-instruction-classifier
    spec:
      containers:
      - name: rs-ingredient-instruction-classifier
        image: julianpoy/ingredient-instruction-classifier:1.1.0
        ports:
        - containerPort: 3000
        env:
        - name: SENTENCE_EMBEDDING_BATCH_SIZE
          value: "100"
        - name: PREDICTION_CONCURRENCY
          value: "1"
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            cpu: 1
            memory: 700Mi
