apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-ingredient-instruction-classifier
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-ingredient-instruction-classifier
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 500m
