apiVersion: v1
kind: Service
metadata:
  name: rs-ingredient-instruction-classifier
spec:
  type: ClusterIP
  selector:
    app: rs-ingredient-instruction-classifier
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

