version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  test_backend:
    working_directory: ~/recipesage
    docker:
      - image: circleci/node:10.16.3
        environment:
          RS_TEST_DB_USERNAME: chefbook
          RS_TEST_DB_PASSWORD: admin
          RS_TEST_DB_DATABASE: chefbook_test
          NODE_ENV: test
          VERBOSE: true
          POSTGRES_DB: chefbook_test
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_PORT: 5432
          POSTGRES_HOST: localhost
          POSTGRES_SSL: false
          POSTGRES_LOGGING: false
          GRIP_URL: http://localhost:5561/
          GRIP_KEY: changeme
      - image: postgres:9.6.9
        environment:
          POSTGRES_USER: chefbook
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: chefbook_test
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - run:
          name: install-deps
          command: 'sudo npm install -g sequelize'
      # -------------- Setup SharedUtils -----------------
      - restore_cache:
          key: sharedutils-dependency-cache-{{ checksum "SharedUtils/package.json" }}
      - run:
          name: install-npm-sharedutils
          command: 'cd SharedUtils && npm install'
      - save_cache:
          key: sharedutils-dependency-cache-{{ checksum "SharedUtils/package.json" }}
          paths:
            - ./SharedUtils/node_modules
      # -------------- Setup Backend -----------------
      - restore_cache:
          key: backend-dependency-cache-{{ checksum "Backend/package.json" }}
      - run:
          name: install-npm-backend
          command: 'cd Backend && npm install'
      - save_cache:
          key: backend-dependency-cache-{{ checksum "Backend/package.json" }}
          paths:
            - ./Backend/node_modules
      - run:
          name: extract-firebase-credentials
          command: cd Backend/src/config && unzip -j -P $credentialskey firebase-credentials.json.zip
      # -------------- Tests -----------------
      - run: # run backend tests
          name: test-backend
          command: cd Backend && npm run test:ci
  build_test_frontend:
    working_directory: ~/recipesage # directory where steps will run
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      # -------------- Setup SharedUtils -----------------
      - restore_cache:
          key: sharedutils-dependency-cache-{{ checksum "SharedUtils/package.json" }}
      - run:
          name: install-npm-sharedutils
          command: 'cd SharedUtils && npm install'
      - save_cache:
          key: sharedutils-dependency-cache-{{ checksum "SharedUtils/package.json" }}
          paths:
            - ./SharedUtils/node_modules
      # -------------- Setup Frontend -----------------
      - restore_cache:
          key: frontend-dependency-cache-{{ checksum "Frontend/package.json" }}
      - run:
          name: install-npm-frontend
          command: 'cd Frontend && npm install'
      - save_cache:
          key: frontend-dependency-cache-{{ checksum "Frontend/package.json" }}
          paths:
            - ./Frontend/node_modules
      # -------------- Tests -----------------
      - run: # lint frontend
          name: lint-frontend
          command: cd Frontend && npm run lint
      - run: # build frontend
          name: build-frontend
          command: cd Frontend && npm run dist
      - persist_to_workspace:
          root: Frontend
          paths:
            - www
  build_push_backend:
    working_directory: ~/recipesage # directory where steps will run
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-login
          command: echo "$DOCKER_PAT" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: tag-and-push-api
          command: ./tag_and_push_image.sh api $CIRCLE_TAG
  push_frontend:
    working_directory: ~/recipesage # directory where steps will run
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: set-frontend-version
          command: sed -i "s/window.version = 'development';/window.version = '${CIRCLE_TAG}';/" www/index.html
      - run:
          name: sync-s3
          command: ./scripts/deploy/push_static_s3.sh $CIRCLE_TAG
workflows:
  version: 2
  build_and_test:
    jobs:
      - test_backend:
          context: "RS API Env Vars"
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build_test_frontend:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build_push_backend:
          requires:
            - test_backend
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/
      - push_frontend:
          requires:
            - build_test_frontend
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*.*/
            branches:
              ignore: /.*/

