apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-browserless
  labels:
    app: rs-browserless
spec:
  selector:
    matchLabels:
      app: rs-browserless
  template:
    metadata:
      labels:
        app: rs-browserless
    spec:
      containers:
      - name: rs-browserless
        image: browserless/chrome:1.28.0-chrome-stable
        ports:
        - containerPort: 3000
        env:
        - name: MAX_CONCURRENT_SESSIONS
          value: "3"
        - name: MAX_QUEUE_LENGTH
          value: "10"
        resources:
          requests:
            cpu: 100m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 700Mi
---
apiVersion: v1
kind: Service
metadata:
  name: rs-browserless
spec:
  type: ClusterIP
  selector:
    app: rs-browserless
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: rs-browserless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-browserless
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 85
