apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rs-browserless
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rs-browserless
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageValue: 400m
