apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    name: {{ include "api.name" . }}
